# Generated by Django 5.2.15 on 2026-07-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(max_length=2000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text="Mark as read once you've seen this message.")),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, help_text='Intro text shown at the top of the modal when a card is opened.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(help_text="e.g. 'Individual Session' or 'Couples Session'", max_length=120)),
                ('duration_minutes', models.PositiveSmallIntegerField(help_text='Length of the session in minutes.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Rate in USD.', max_digits=7)),
                ('note', models.CharField(blank=True, help_text='Optional note shown beneath the rate row.', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Session Rate',
                'verbose_name_plural': 'Session Rates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(default='Nurtured Story', max_length=120)),
                ('tagline', models.CharField(default='Relational and Sex Counseling', max_length=200)),
                ('phone', models.CharField(default='470-599-5630', max_length=30)),
                ('email', models.EmailField(default='shel@nurturedstory.com', max_length=254)),
                ('about_practice', models.TextField(blank=True, help_text="The 'About the Practice' blurb shown on the home page.")),
                ('sliding_scale_note', models.CharField(blank=True, default='✦ Sliding scale available — reach out to discuss what works for you.', max_length=300)),
                ('footer_text', models.CharField(blank=True, default='Copyright 2026 Nurtured Story', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shel Pohnan', max_length=120)),
                ('credentials', models.CharField(blank=True, default='APC · Certified Sex Therapist', help_text="Shown under the therapist name, e.g. 'APC · Certified Sex Therapist'", max_length=200)),
                ('bio', models.TextField(blank=True, help_text="Full bio shown in the 'About' card on the home page.")),
                ('photo', models.ImageField(blank=True, help_text='Profile photo displayed on the home page.', null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Therapist Profile',
                'verbose_name_plural': 'Therapist Profile',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, help_text='Optional display date for the training.', null=True)),
                ('signup_url', models.URLField(blank=True, help_text='Optional link for sign-ups or more info.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False, help_text="Only published trainings appear on the site. When none are published the page shows 'None currently available'.")),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, help_text='Short description shown beneath the link.', max_length=400)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.resourcecategory')),
            ],
            options={
                'verbose_name': 'Resource Link',
                'verbose_name_plural': 'Resource Links',
                'ordering': ['order'],
            },
        ),
    ]
