# Generated by Django 5.2.15 on 2026-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_initial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrate',
            name='booking_message',
            field=models.TextField(blank=True, default='', help_text="Pre-filled message inserted into the contact form when a visitor clicks 'Book' on this rate row. Use it to confirm the session type they're enquiring about, e.g. 'Hi, I'm interested in booking an Individual Session (50 min, $150). Please let me know your availability.'"),
        ),
        migrations.AlterField(
            model_name='sessionrate',
            name='note',
            field=models.CharField(blank=True, help_text='Optional note shown beneath this rate row.', max_length=300),
        ),
    ]
