# Generated by Django 5.2.15 on 2026-07-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_add_session_rate_booking_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='blurb',
            field=models.TextField(blank=True, help_text='Bullet points for this service, one per line.'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text="Card heading, e.g. 'Individual Sex Therapy'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='label',
            field=models.CharField(help_text='Short display name — shown as fallback if category is blank.', max_length=300),
        ),
    ]
