# Generated by Django 5.2.15 on 2026-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_seed_services_with_blurbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a PDF or other file. If provided, this takes priority over the URL field.', null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True, help_text='External URL. Leave blank if uploading a file instead.'),
        ),
    ]
