# Generated by Django 5.2.15 on 2026-07-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_add_resource_link_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensurePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Georgia LPC/APC Licensure Consultation', max_length=200)),
                ('page_lede', models.CharField(default='Support for counselors-in-training and associate-level clinicians', max_length=300)),
                ('consult_intro', models.TextField(default='Navigating the LPC/APC licensure process can feel overwhelming, especially when trying to understand application requirements, documentation, supervision requirements, and renewal processes. I offer consultation to help counselors-in-training and associate-level clinicians better understand and navigate the Georgia licensure process.', help_text='Opening paragraph in the Licensure Consultation card.')),
                ('consult_items', models.TextField(default='Guidance on the Georgia LPC/APC application process\nReviewing application requirements and documentation\nSupport with understanding supervision requirements\nAssistance navigating the renewal process / CE requirements\nGeneral guidance on maintaining licensure requirements', help_text='Bullet points for the consultation card, one per line.')),
                ('consult_rate_label', models.CharField(default='Consultation Rate', max_length=100)),
                ('consult_rate', models.CharField(default='$50 / hour', max_length=50)),
                ('renewal_intro', models.TextField(default='This consultation includes a review of your current continuing education (CE) credits, a detailed report outlining any remaining CE requirements, and a curated list of available CE opportunities to help you complete your renewal requirements.', help_text='Body text for the CE Renewal Consultation card.')),
                ('renewal_rate_label', models.CharField(default='Rate', max_length=100)),
                ('renewal_rate', models.CharField(default='$75', max_length=50)),
                ('disclaimer', models.TextField(default='This service is intended to provide support and clarification throughout the licensure process. It does not replace guidance from the Georgia Composite Board, and applicants are responsible for ensuring they meet all current licensure requirements.', help_text='Disclaimer note shown beneath both cards.')),
            ],
            options={
                'verbose_name': 'Licensure Page',
                'verbose_name_plural': 'Licensure Page',
            },
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='credentials',
            field=models.CharField(blank=True, default='APC · Sex Therapist', help_text="Shown under the therapist name, e.g. 'APC · Sex Therapist'", max_length=200),
        ),
    ]
