# Generated by Django 5.2.15 on 2026-07-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_add_licensure_booking_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_practice_heading',
            field=models.CharField(default='About the Practice', help_text="Heading for the 'About the Practice' card on the home page.", max_length=200),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='about_heading',
            field=models.CharField(blank=True, default='', help_text="Heading for the 'About' card on the home page. Defaults to 'About {name}' if left blank.", max_length=200),
        ),
        migrations.AlterField(
            model_name='licensurepage',
            name='page_title',
            field=models.CharField(default='Georgia LPC/APC Licensure  Consultation', max_length=200),
        ),
    ]
