# Generated by Django 5.2.15 on 2026-07-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_seed_current_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBusinessSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Decatur', help_text="City where sessions are offered in person, e.g. 'Decatur'", max_length=100)),
                ('state', models.CharField(blank=True, default='GA', help_text="State abbreviation, e.g. 'GA'", max_length=50)),
            ],
            options={
                'verbose_name': 'Local Business SEO',
                'verbose_name_plural': 'Local Business SEO',
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('pricing', 'Pricing'), ('resources', 'Resources'), ('trainings', 'Trainings'), ('licensure', 'Licensure')], help_text='Which page these SEO settings apply to.', max_length=20, unique=True)),
                ('meta_title', models.CharField(blank=True, default='', help_text="Browser tab title and Google headline. Keep under 70 characters. Leave blank to use the page's default title.", max_length=70)),
                ('meta_description', models.CharField(blank=True, default='', help_text='Shown under the page title in Google search results. Keep under 160 characters.', max_length=160)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['page'],
            },
        ),
    ]
