# Generated by Django 5.2.15 on 2026-07-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_seed_page_seo_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_recipient_email',
            field=models.EmailField(blank=True, default='shel@nurturedstory.com', help_text='Email address that receives contact form submissions. Can be the same as the display email or a different inbox.', max_length=254),
        ),
    ]
